can: gs_usb: gs_usb_receive_bulk_callback(): fix DMA memory leak
In gs_can_open() GS_MAX_RX_URBS URBs and coherent buffers are
allocated, anchored in struct gs_usb::rx_submitted and then submitted,
but there is nothing, that frees them:

1) In the callback function gs_usb_receive_bulk_callback() the URB is
   resubmitted.
2) In the gs_can_close() function the URBs are simply killed, but
   URB_FREE_BUFFER is not set (see gs_can_close()) and this flag cannot
   be used with coherent buffers.

All allocated buffers have to be freed with usb_free_coherent()
explicitly.

This patch uses the fact, that the callback of all URBs, once they are
submitted, will be called once, even if the URB is killed. In
gs_usb_receive_bulk_callback() more urb->status errors are treated as
fatal...

| imx_usb 2184200.usb: dma_pool_destroy buffer-64, 500988e5 busy

can: gs_usb: detach device on reception of invalid USB data

The received data contains the channel the received data is associated
with. If the channel number is bigger than the actual number of
channels assume broken or malicious USB device and shut it down.

This fixes the error found by clang:

| drivers/net/can/usb/gs_usb.c:386:6: error: variable 'dev' is used
|                                     uninitialized whenever 'if' condition is true
|         if (hf->channel >= GS_MAX_INTF)
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~
| drivers/net/can/usb/gs_usb.c:474:10: note: uninitialized use occurs here
|                           hf, dev->gs_hf_size, gs_usb_receive_bulk_callback,
|                               ^~~

Link: https://lore.kernel.org/all/20211210091158.408326-1-mkl@pengutronix.de
Fixes: d08e973a77d1 ("can: gs_usb: Added support for the GS_USB CAN devices")
Cc: stable@vger.kernel.org
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
(cherry picked from commit 1758f6e2a91d8ca1fde30c56be5af76854005f99)